### PR TITLE
[JENKINS-35463] Use bouncycastle-api-plugin

### PR DESCRIPTION
**Pull request by armfergom**
[JENKINS-35463](https://issues.jenkins-ci.org/browse/JENKINS-35463)

@reviewbybees

### CODE REVIEW

**Comment by recena** [comment]
🐝

**Comment by andresrc** [comment]
:bee:

**Comment by alvarolobato** [comment]
🐝

**Comment by amuniz** [comment]
:bee:

**Comment by recena** [comment]
@reviewbybees done

**Pull request merged**
